- hosts: localhost 
  vars_files:
    - ./vars/roles_repos.yml
  tasks: 
  - name: Cloning Collection main repo 
    ansible.builtin.git:
      repo: "{{main_collection.repo}}"
      dest: "{{main_collection.clone_dir}}"
    environment:
       GIT_TERMINAL_PROMPT: 0 # reports "terminal prompts disabled" on missing password
  
  - name: Adding each role to the collection
    git_subtree: 
      source: "{{item.source}}"
      ref: "{{item.ref}}"
      prefix: "{{item.prefix}}"
      squash: true
      commit_message: "Add subtree {{item.prefix}} to the collection"
      working_directory: "{{main_collection.clone_dir}}"
    register: subtree_output
    environment:
      GIT_TERMINAL_PROMPT: 0
    loop: "{{subtrees}}"
  - name: debug
    debug:
      var: subtree_output
  - name: Add collection content to git
    ansible.builtin.shell: |
      git config --global user.name "automated collection packaging"
      git config --global user.email "rhamdi@redhat.com"
      git push
    args:
      chdir: "{{main_collection.clone_dir}}"
    register: output
