- hosts: localhost 
  vars:
    git_token: 
    subtrees:
      - source: git@github.com:riadhhamdi/demo_role1.git  ## Change with your own role (https or ssh) 
        squash: true 
        ref: main
        prefix: roles/role1
      - source: git@github.com:riadhhamdi/demo_role2.git  ## Change with your own role (https or ssh) 
        squash: true 
        ref: main
        prefix: roles/role2
  tasks: 
  - name: Avoid hanging when http(s) password is missing
    ansible.builtin.git:
      repo: git@github.com:riadhhamdi/demo.collection.git
      dest: /tmp
    environment:
       GIT_TERMINAL_PROMPT: 0 # reports "terminal prompts disabled" on missing password
  
  - name: Adding each role to the collection
    git_subtree: 
      source: "{{item.source}}"
      ref: "{{item.ref}}"
      prefix: "{{item.prefix}}"
      squash: true
      commit_message: "Add subtree {{item.prefix}} to the collection"
      working_directory: /tmp/demo.collection
    register: subtree_output
    environment:
      GIT_TERMINAL_PROMPT: 0
    loop: "{{subtrees}}"
  - name: debug
    debug:
      var: subtree_output
  - name: Add collection content to git
    ansible.builtin.shell: |
      git config --global user.name "automated collection packaging"
      git config --global user.email "rhamdi@redhat.com"
      git add -A && git commit -m "Automated Commit by Ansible" && git push
    args:
      chdir: /tmp/demo.collection
    register: output
    failed_when: >
      output.msg != "" and
      ("error" in output.msg or
      "conflict" in output.msg or
      "Errno" in output.msg or
      "fatal" in output.msg or
      (output.stdout != "" and
      "nothing to commit, working tree clean" not in output.stdout) or
      (output.stderr != ""))
